export const CDE = {};

CDE.MAGICS = {
  internalcinnabar: {
    background: "linear-grey",
    label: "CDE.InternalCinnabar",
    aspectlabel: "CDE.Metal",
    speciality: {
      essence: {
        label: "CDE.Essence",
        classicon: "icon-yin",
        icon: "/systems/chroniquesdeletrange/images/cde_yin.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_metal.png",
        labelicon: "Yin",
        labelelement: "CDE.Metal",
      },
      mind: {
        label: "CDE.Mind",
        classicon: "icon-yin",
        icon: "/systems/chroniquesdeletrange/images/cde_yin.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_eau.png",
        labelicon: "Yin",
        labelelement: "CDE.Water",
      },
      purification: {
        label: "CDE.Purification",
        classicon: "icon-yinyang",
        icon: "/systems/chroniquesdeletrange/images/yin_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_terre.png",
        labelicon: "Yin/Yang",
        labelelement: "CDE.Earth",
      },
      manipulation: {
        label: "CDE.Manipulation",
        classicon: "icon-yang",
        icon: "/systems/chroniquesdeletrange/images/cde_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_feu.png",
        labelicon: "Yang",
        labelelement: "CDE.Fire",
      },
      aura: {
        label: "CDE.Aura",
        classicon: "icon-yang",
        icon: "/systems/chroniquesdeletrange/images/cde_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_bois.png",
        labelicon: "Yang",
        labelelement: "CDE.Wood",
      },
    },
  },
  alchemy: {
    background: "linear-blue",
    label: "CDE.Alchemy",
    aspectlabel: "CDE.Water",
    speciality: {
      acupuncture: {
        label: "CDE.Acupuncture",
        classicon: "icon-yin",
        icon: "/systems/chroniquesdeletrange/images/cde_yin.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_metal.png",
        labelicon: "Yin",
        labelelement: "CDE.Metal",
      },
      elixirs: {
        label: "CDE.Elixirs",
        classicon: "icon-yin",
        icon: "/systems/chroniquesdeletrange/images/cde_yin.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_eau.png",
        labelicon: "Yin",
        labelelement: "CDE.Water",
      },
      poisons: {
        label: "CDE.Poisons",
        classicon: "icon-yinyang",
        icon: "/systems/chroniquesdeletrange/images/yin_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_terre.png",
        labelicon: "Yin/Yang",
        labelelement: "CDE.Earth",
      },
      arsenal: {
        label: "CDE.Arsenal",
        classicon: "icon-yang",
        icon: "/systems/chroniquesdeletrange/images/cde_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_feu.png",
        labelicon: "Yang",
        labelelement: "CDE.Fire",
      },
      potions: {
        label: "CDE.Potions",
        classicon: "icon-yang",
        icon: "/systems/chroniquesdeletrange/images/cde_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_bois.png",
        labelicon: "Yang",
        labelelement: "CDE.Wood",
      },
    },
  },
  masteryoftheway: {
    background: "linear-brown",
    label: "CDE.MasteryOfTheWay",
    aspectlabel: "CDE.Earth",
    speciality: {
      curse: {
        label: "CDE.Curse",
        classicon: "icon-yin",
        icon: "/systems/chroniquesdeletrange/images/cde_yin.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_metal.png",
        labelicon: "Yin",
        labelelement: "CDE.Metal",
      },
      transfiguration: {
        label: "CDE.Transfiguration",
        classicon: "icon-yin",
        icon: "/systems/chroniquesdeletrange/images/cde_yin.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_eau.png",
        labelicon: "Yin",
        labelelement: "CDE.Water",
      },
      necromancy: {
        label: "CDE.Necromancy",
        classicon: "icon-yinyang",
        icon: "/systems/chroniquesdeletrange/images/yin_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_terre.png",
        labelicon: "Yin/Yang",
        labelelement: "CDE.Earth",
      },
      climatecontrol: {
        label: "CDE.ClimateControl",
        classicon: "icon-yang",
        icon: "/systems/chroniquesdeletrange/images/cde_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_feu.png",
        labelicon: "Yang",
        labelelement: "CDE.Fire",
      },
      goldenmagic: {
        label: "CDE.GoldenMagic",
        classicon: "icon-yang",
        icon: "/systems/chroniquesdeletrange/images/cde_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_bois.png",
        labelicon: "Yang",
        labelelement: "CDE.Wood",
      },
    },
  },
  exorcism: {
    background: "linear-red",
    label: "CDE.Exorcism",
    aspectlabel: "CDE.Fire",
    speciality: {
      invocation: {
        label: "CDE.Invocation",
        classicon: "icon-yin",
        icon: "/systems/chroniquesdeletrange/images/cde_yin.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_metal.png",
        labelicon: "Yin",
        labelelement: "CDE.Metal",
      },
      tracking: {
        label: "CDE.Tracking",
        classicon: "icon-yin",
        icon: "/systems/chroniquesdeletrange/images/cde_yin.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_eau.png",
        labelicon: "Yin",
        labelelement: "CDE.Water",
      },
      protection: {
        label: "CDE.Protection",
        classicon: "icon-yinyang",
        icon: "/systems/chroniquesdeletrange/images/yin_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_terre.png",
        labelicon: "Yin/Yang",
        labelelement: "CDE.Earth",
      },
      punishment: {
        label: "CDE.Punishment",
        classicon: "icon-yang",
        icon: "/systems/chroniquesdeletrange/images/cde_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_feu.png",
        labelicon: "Yang",
        labelelement: "CDE.Fire",
      },
      domination: {
        label: "CDE.Domination",
        classicon: "icon-yang",
        icon: "/systems/chroniquesdeletrange/images/cde_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_bois.png",
        labelicon: "Yang",
        labelelement: "CDE.Wood",
      },
    },
  },
  geomancy: {
    background: "linear-green",
    label: "CDE.Geomancy",
    aspectlabel: "CDE.Wood",
    speciality: {
      neutralization: {
        label: "CDE.Neutralization",
        classicon: "icon-yin",
        icon: "/systems/chroniquesdeletrange/images/cde_yin.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_metal.png",
        labelicon: "Yin",
        labelelement: "CDE.Metal",
      },
      divination: {
        label: "CDE.Divination",
        classicon: "icon-yin",
        icon: "/systems/chroniquesdeletrange/images/cde_yin.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_eau.png",
        labelicon: "Yin",
        labelelement: "CDE.Water",
      },
      earthlyprayer: {
        label: "CDE.EarthlyPrayer",
        classicon: "icon-yinyang",
        icon: "/systems/chroniquesdeletrange/images/yin_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_terre.png",
        labelicon: "Yin/Yang",
        labelelement: "CDE.Earth",
      },
      heavenlyprayer: {
        label: "CDE.HeavenlyPrayer",
        classicon: "icon-yang",
        icon: "/systems/chroniquesdeletrange/images/cde_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_feu.png",
        labelicon: "Yang",
        labelelement: "CDE.Fire",
      },
      fungseoi: {
        label: "CDE.Fungseoi",
        classicon: "icon-yang",
        icon: "/systems/chroniquesdeletrange/images/cde_yang.png",
        elementicon: "/systems/chroniquesdeletrange/images/cde_bois.png",
        labelicon: "Yang",
        labelelement: "CDE.Wood",
      },
    },
  },
};

CDE.SUBTYPES = {
  weapon: {
    id: "weapon",
    label: "CDE.Weapon",
  },
  armor: {
    id: "armor",
    label: "CDE.Armor",
  },
  sanhei: {
    id: "sanhei",
    label: "CDE.Sanhei",
  },
  other: {
    id: "other",
    label: "CDE.Other",
  },
};